name: Link Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash ca-certificates

      - name: Check links
        id: report
        run: |
          mkdir -p reports
          bash link_checker/check.sh README.md --markdown > reports/${{ github.event.pull_request.number }}.md

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: reports/${{ github.event.pull_request.number }}.md
          retention-days: 5
